apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: partner-catalog
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: partner-catalog
    app.kubernetes.io/part-of: partner-catalog-1
  name: partner-catalog
spec:
  rules:
  - host: partner-catalog-rh-ee-sombaner-tenant.api-y00zljez-centralindia-aroapp-io:6443
    http:
      paths:
      - backend:
          service:
            name: partner-catalog
            port:
              number: 8081
        path: /
        pathType: ImplementationSpecific
status:
  loadBalancer: {}
